name: sqflite_sqlcipher
homepage: https://github.com/davidmartos96/sqflite_sqlcipher
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine. (SqlCipher support)
version: 3.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.davidmartos96.sqflite_sqlcipher
        pluginClass: SqfliteSqlCipherPlugin
      ios:
        pluginClass: SqfliteSqlCipherPlugin
      macos:
        pluginClass: SqfliteSqlCipherPlugin


dependencies:
  flutter:
    sdk: flutter
  synchronized: '>=3.0.0 <4.0.0'
  path: '>=1.8.0 <3.0.0'
  sqflite_common: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  process_run: ^0.13.1
  flutter_test:
    sdk: flutter
